CREATE DATABASE DATA_BASE_EMPTY;
GO

USE DATA_BASE_EMPTY;
GO

--Criar login no servidor
CREATE LOGIN AdminLocal WITH PASSWORD = 'Admin123';

--Criar usuário no banco
USE DATA_BASE_EMPTY;
CREATE USER AdminLocal FOR LOGIN AdminLocal;

--Dar permissões
ALTER ROLE db_owner ADD MEMBER AdminLocal;

--Criar tabela de tipos de usuário
CREATE TABLE TB_XML_EXTRACT (
    ID_XML_EXTRACT NUMERIC(15,0) IDENTITY(1,1) PRIMARY KEY NOT NULL,
	NUM_NOTA NVARCHAR(20) NOT NULL,
    CNPJ_PRESTADOR NVARCHAR(14) NOT NULL,
	CNPJ_TOMADOR NVARCHAR(14) NOT NULL,
	DATA_EMISSAO DATETIME2 NOT NULL,
	DESCRICAO_SERVICO NVARCHAR(MAX) NULL,
	VALOR_TOTAL DECIMAL(18,2) NOT NULL
);
GO
